baseURL: https://shiny-kitten-777df7.netlify.app
languageCode: en-us
title: John Doe
theme: mini-folio

author: Paul Walczak

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50

markup:
  highlight:
    codeFences: true
    noClasses: true
    style: monokai        # TODO : find a way to change code theme

Params:
  logo:
    enable: true
    #path: /img/profile_picture.jpeg
    #url: https://polo-wolo.github.io/portfolio/

  profile:
    title: "Paul Walczak"
    subtitle: "4th year student in generalist engineering school"
    imageUrl: "img/profile_picture.jpeg" # optional
    imageWidth: 180
    imageHeight: 180
    cv:
      - name: French CV
        filePath: "/pdf/french_cv.pdf"
      - name: English CV
        filePath: "/pdf/english_cv.pdf"

    mail: john.doe@gmail.com
    phone: +33 0 12 34 56 78
    socials:
        - name: linkedin
          svg : linkedin-in
          link: https://www.linkedin.com/in/paul-walczak-639106194/ 
        - name: instagram
          svg : instagram
          link: 
        - name: facebook
          svg : facebook
          link: 
        - name: github
          svg : github
          link: 
        - name: gitlab
          svg : gitlab
          link: 

  website_logo : true
  timeline_overflow : false       # training timeline dotted lines
  ShowPostNavLinks : true
  repo_url : https://github.com/Polo-Wolo/hugo-enib

  # Sections
  experience:
    #title: Custom title
    enable: true

  education:
    title: Custom Education title
    enable: true

  volunteering:
    #title: Custom title
    enable: false
    list:
      - organisation: Nous Existons
        logo_path:
        date: 2021-2023
        content:
          - Scientific mediation that aims to raise awareness of the sensitivity and fragility of the seabed. The project is suported by ISblue, ISblueHUB and Ifremer.
        city: Brest
        country: FRANCE 
      - organisation: Cordées de la Réussite
        logo_path:
        date: 2021-2022
        content:
          - A French national education scheme that aims to encourage academic ambition among secondary school students.
        city: Brest
        country: FRANCE
      - organisation: Summer Camp Animator
        logo_path:
        date: 2020-2021
        content:
          - Summer camp animator during 2 summers. With youngs from 11 to 15 years old.
        city: Mont Saint-Michel
        country: FRANCE

  training:
    #title: Custom title
    enable: true
    list:
      - title: Generalist Engineer
        date: 2019 - 2024
        content: 
          - ENIB - École Nationale d'Ingénieur de Brest
          - General - Electronics, Mechatronics, Computer Science
          - Signal and image processing option
        city: Plouzané
        country: FRANCE
      - title: Sauveteur Secouriste du Travail
        date: Jan. 2022
        content: 
          - First Aid at Work
        city: Plouzané
        country: FRANCE
      - title: Boat Licence
        date: July 2021
        content: 
          - Costal boat licence
        city: Brest
        country: FRANCE
      - title: PSE1
        date: May 2021
        content: 
          - First Aid in Team Level 1 certification
        city: Brest
        country: FRANCE
      - title: Scientific Baccalaureat
        date: July 2019
        content: 
          - Digital science and European Section
        city: Châteaulin
        country: FRANCE
      - title: BNSSA
        date: Avr. 2019
        content: 
          - Awarded of Brevet National de Sécurité et de Sauvetage Aquatique (National Aquatic Safety and Rescue Certificate).
          - This is a French aquatic safety certification.
        city: Landerneau
        country: FRANCE
      - title: PET for School
        date: June 2017
        content: 
          - Awarded PET for School.
          - English level = B1 Cambridge.
        city: Châteaulin
        country: FRANCE

  skills:
    #title: Custom title
    enable: true
    types:
      - name: Microcontroller programming
        svg : microchip-solid
        list:
          - Arduino
          - STM32
          - CM33
      - name: Programming
        svg : code-solid
        list:
          - Python
          - C
          - C++
          - QT Creator
          - Matlab
      - name: Web development
        svg : desktop-solid
        list:
          - Vue
          - Flask
          - Hugo
          - TailwindCSS
          - Jinja
      - name: CAD
        svg : cube-solid
        list:
          - Autodesk Fusion 360
          - Gazebo
          - CATIA
          - EAGLE
          - Blender (newbie)
      - name: Languages
        svg : language-solid
        list:
          - French (native)
          - English (proficient)

  hobbies:
    #title: Custom title
    enable: true
    types:
      - name: Microcontroller programming
        svg : microchip-solid
        list:
          - Arduino
          - STM32
          - CM33